### ISSUE TITLE
graphs not found after compiling and running the project 

### ISSUE THREAD

**Issue by avionicscode** [sean-chester/SkyBench#2]
**thank you** for sharing this great project
i am using **Ubuntu 18.04** 
i followed your description in the **Readme** file 

when i run `make all DIMS=8`

the project compiled and the **.o** files created in **bin** directory 
then after i run `./bin/SkyBench -f workloads/nba-U-8-17264.csv`
and 
`./runExp.sh -p -i workloads/ -t 8 -c 1000000 -d "2 4 6 8 10 12 14 16 18 20 22 24" -s "bskytree hybrid"`
 i get **.csv** files in the result folders

i want to know how do you get the graphs in figure 5 fig 6 ... and figure 13 in your published paper ICDE 2015 (Scalable Parallelization of Skyline Computation for Multicore Processors).

please is this the code not enough to generate those graphs

if i compile the project in a **4 core** laptop are there changes i can make to your code to get the results in your published paper ?

i changed threads="4"

but it not worked

**Comment by sean-chester** [comment]
@avionicscode , thanks for the questions and sorry for the slow reply!

We **did not** include in this repository the code used to generate the plots. This was done in _LaTeX_, using the _pgfplots_ package. _pgfplots_ reads the .csv files directly. You should be able to use any plotting software (e.g., _gnuplot_ or _MS Excel_) to recreate similar plots.

For a 4-core processor with hyper-threading enabled, it probably does not make sense to scale the experiments beyond 8 threads. You can control the number of threads in the `./runExp.sh` script with the `-t [num-threads]` flag. Is this what you have already tried?
